# if (EXISTS ${CMAKE_SOURCE_DIR}/.options.cmake)
# include(.options)
# message(STATUS ">>> options decl file (.options.cmake) loaded")
# else ()
# message(STATUS ">>> options decl file (.options.cmake) ignored")
# set(BASENAME prj)
# endif ()

# if (EXISTS ${CMAKE_SOURCE_DIR}/.options.local.cmake)
# include(.options.local)
# message(STATUS ">>> options.local decl file (.options.local.cmake) loaded")
# endif ()

set(BASENAME prj)
safe_include(.options.cmake "options definitions file")
safe_include(.options.local.cmake "local options definitions file")