set(CMAKE_SCRIPTS_DIR ${CMAKE_SOURCE_DIR}/${CMAKE_SCRIPTS})
get_filename_component(CMAKE_ROOT_DIR ${CMAKE_SCRIPTS_DIR} DIRECTORY)

# set(EXECUTABLE_OUTPUT_PATH "${CMAKE_SOURCE_DIR}/bin")
# set(LIBRARY_OUTPUT_PATH "${CMAKE_SOURCE_DIR}/bin/lib")
# set(ARCHIVE_OUTPUT_PATH "${CMAKE_SOURCE_DIR}/bin/lib")
# #set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/test)
# set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/bin")
#
# #link_directories(BEFORE ${LIBRARY_OUTPUT_PATH} ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
if (${USE_DEBUG})
	# set(EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR}/debug)
	set(EXECUTABLE_OUTPUT_PATH "${CMAKE_SOURCE_DIR}/bin")
	set(LIBRARY_OUTPUT_PATH "${EXECUTABLE_OUTPUT_PATH}/lib/${CMAKE_BUILD_NAME}")
	set(ARCHIVE_OUTPUT_PATH "${EXECUTABLE_OUTPUT_PATH}/lib/${CMAKE_BUILD_NAME}")
else ()
	set(EXECUTABLE_OUTPUT_PATH "${CMAKE_SOURCE_DIR}/bin/${CMAKE_BUILD_NAME}")
	set(LIBRARY_OUTPUT_PATH "${EXECUTABLE_OUTPUT_PATH}/lib/${CMAKE_BUILD_NAME}")
	set(ARCHIVE_OUTPUT_PATH "${EXECUTABLE_OUTPUT_PATH}/lib/${CMAKE_BUILD_NAME}")
endif ()

message(STATUS "EXECUTABLE_OUTPUT_PATH = ${EXECUTABLE_OUTPUT_PATH} ...")

# set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/test)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${EXECUTABLE_OUTPUT_PATH}")

# Note that CMAKE_GENERATED_DIR is NOT a cmake builtin variable.
set(CMAKE_GENERATED_DIR "${CMAKE_BINARY_DIR}/generated")
mark_as_advanced(CMAKE_GENERATED_DIR)

message("   ./cmake/target-dirs.cmake:34 : ")
message("   > CMAKE_SCRIPTS_DIR:        ${CMAKE_SCRIPTS_DIR}")
message("   > CMAKE_ROOT_DIR:           ${CMAKE_ROOT_DIR}")
message("   > CMAKE_SOURCE_DIR:         ${CMAKE_SOURCE_DIR}")
message("   > CMAKE_BINARY_DIR:         ${CMAKE_BINARY_DIR}")
message("   > CMAKE_GENERATED_DIR:      ${CMAKE_GENERATED_DIR}")
message("   > EXECUTABLE_OUTPUT_PATH:   ${EXECUTABLE_OUTPUT_PATH}")

# set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/sm-lib)
# set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/sm-lib)
# set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

# set(EXECUTABLE_OUTPUT_PATH "${CMAKE_SOURCE_DIR}/bin")
# set(LIBRARY_OUTPUT_PATH "${CMAKE_SOURCE_DIR}/sm-lib")
# link_directories(BEFORE "${CMAKE_SOURCE_DIR}/sm-lib")

# set(V alpha beta gamma)
# message(${V})
#
# foreach(i ${V})
# message(${i})
# endforeach()
